### ISSUE TITLE
百度登录失败

### ISSUE THREAD

**Issue by 15871722713** [Kr1s77/awesome-python-login-model#25]

**Comment by 15871722713** [comment]
python baidu.py 
Traceback (most recent call last):
  File "baidu.py", line 124, in <module>
    token = (get_token())
  File "baidu.py", line 100, in get_token
    token_callback = get_callback()
  File "baidu.py", line 67, in get_callback
    a.append(loopabc[n % 36])
TypeError: string indices must be integers, not float
